import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

export interface Location {
  display: string;
  range: number | null;
  shelf: string | null;
}

export interface Item {
  id: string;
  title: string;
  titleArabic: string;
  authors: string[];
  editors: string[];
  contributors: string[];
  year: number | null;
  date: string;
  publisher: string;
  place: string;
  series: string;
  pages: string;
  isbn: string;
  issn: string;
  oclc: string;
  languages: string[];
  library: string;
  location: Location;
  subjects: string[];
  itemType: string;
  search: string;
  skeleton: string;
}

export interface Facet {
  value: string;
  count: number;
}

interface Catalog {
  items: Item[];
  facets: Record<string, Facet[]>;
  count: number;
}

/**
 * The catalog is generated by tools/build_catalog.py from the Zotero
 * export. It is read at build time only -- nothing here ships to the browser
 * except the compact index emitted by catalog/index.json.ts.
 */
// Resolved from the Astro project root rather than import.meta.url, which
// does not survive bundling into the prerender entrypoint.
const path = resolve(process.cwd(), '../data/catalog.json');
const catalog = JSON.parse(readFileSync(path, 'utf-8')) as Catalog;

export const items = catalog.items;
export const facets = catalog.facets;
export const count = catalog.count;

export function byId(id: string): Item | undefined {
  return items.find((i) => i.id === id);
}

/**
 * A comparison key for matching names across sources.
 *
 * The catalog records the library as "Rif'at al-Sa'id Library" while the
 * site writes it "Rifʿat al-Saʿīd Library". Both are the same place, so
 * matching folds away diacritics, apostrophes, and spacing rather than
 * relying on the two spellings being kept in sync by hand.
 */
export function nameKey(s: string): string {
  return s
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
}

const ARABIC_LETTER = /[؀-ۿݐ-ݿﭐ-﷿ﹰ-﻿]/g;
const LATIN_LETTER = /[A-Za-zÀ-ɏḀ-ỿ]/g;

/**
 * Whether a value should be typeset as Arabic.
 *
 * Presence of Arabic is not enough: cataloged names are routinely mixed, as
 * in "Ghazālī/غزالي, ʿAbd al-Munʿim/عبد المنعم". Marking a mixed string as
 * Arabic makes the whole line right-to-left and reorders the Latin parts,
 * so only predominantly Arabic values get the treatment. Mixed values stay
 * left-to-right and let the bidirectional algorithm lay out the Arabic runs.
 */
export function isArabicDominant(text: string): boolean {
  const arabic = (text.match(ARABIC_LETTER) ?? []).length;
  const latin = (text.match(LATIN_LETTER) ?? []).length;
  return arabic > 0 && arabic > latin;
}

/** A display title, falling back to the Arabic form for untranslated records. */
export function displayTitle(item: Item): string {
  return item.title || item.titleArabic;
}

/** "Author, Year" style attribution line, omitting whatever is missing. */
export function credit(item: Item): string {
  const who = item.authors[0] ?? item.editors[0] ?? '';
  return [who, item.year ? String(item.year) : ''].filter(Boolean).join(', ');
}

/**
 * Chicago-ish citation for a physical holding, matching the form the center
 * already asks researchers to use.
 */
export function citation(item: Item, siteName: string): string {
  const parts = [
    item.authors.join('; '),
    `"${displayTitle(item)}."`,
    item.date || 'n.d.',
    `${siteName}, ${item.library}`,
    item.location.display,
  ].filter(Boolean);
  return parts.join(' ') + '.';
}

/**
 * Facets worth exposing as filters. Subject terms are deliberately excluded:
 * with 73% of them used exactly once they do not yet partition the
 * collection usefully (see docs/cataloging-recommendations.md).
 */
export const filterFacets = [
  { key: 'languages', label: 'Language', values: facets.languages },
  { key: 'decades', label: 'Decade', values: facets.decades },
  { key: 'ranges', label: 'Shelf range', values: facets.ranges },
] as const;
